#!/usr/bin/env bash

"${HOME}/.local/opt/update_colors.py"

xsetroot -cursor_name left_ptr

pgrep --exact sxhkd >/dev/null || sxhkd     &
pgrep --exact polybar >/dev/null || polybar &
[ -f "${HOME}/.fehbg" ] && ${HOME}/.fehbg   &

bspc monitor --reset-desktops 1 2 3 4 5
bspc desktop --layout monocle

bspc config border_width 5
bspc config window_gap 10
bspc config split_ratio 0.5

source "${HOME}/.config/bspwm/colors"
