#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
picom --experimental-backend &
$HOME/.fehbg &
$HOME/.config/polybar/launch.sh &
[ ! -s ~/.config/mpd/pid ] && mpd &

bspc monitor -d 1 2 3 4 5

bspc config border_width 4
bspc config window_gap 10
bspc config split_ratio .5
bspc rule -a Alacritty state=floating
bspc config focused_border_color '#70d38b'
