[window]
dynamic_padding = true
padding         = { x = 5, y = 5 }

[cursor]
style          = { shape = "Block", blinking = "Always" }
blink_interval = 500
blink_timeout  = 0

[font]
size        = 10
normal      = { family = "JetBrainsMono Nerd Font", style = "Regular"          }
italic      = { family = "JetBrainsMono Nerd Font", style = "Italic"           }
bold        = { family = "JetBrainsMono Nerd Font", style = "ExtraBold"        }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "ExtraBold Italic" }

[keyboard]
bindings = [
  { key = "T",   mods = "Control|Shift", chars = "\uE000" },
  { key = "Tab", mods = "Control",       chars = "\uE001" },
  { key = "Tab", mods = "Control|Shift", chars = "\uE002" },
  { key = "W",   mods = "Control|Shift", chars = "\uE003" },
]

[colors.primary]
background = "#000000"
foreground = "#ffffff"
